--CREATE USER TABLE
DROP TABLE IF EXISTS USER_DEATAILS
;

CREATE TABLE USER_DEATAILS(
    USER_ID             BIGSERIAL         NOT NULL,
    USER_NAME           VARCHAR           NOT NULL,
    USER_EMAIL          VARCHAR           NOT NULL,
    USER_PASSWORD       TEXT              NOT NULL,
    USER_ROLE           VARCHAR           NOT NULL,
    USER_ACCESS         VARCHAR           NOT NULL,
    USER_STATUS         VARCHAR           NOT NULL,
    PRIMARY KEY (USER_ID)
);