name: Check Branch Naming Convention

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch naming convention
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          echo "Checking branch name: $BRANCH_NAME"

          if [[ "$BRANCH_NAME" =~ ^feature\/[a-zA-Z0-9_-]+\/[a-zA-Z0-9._-]+$ ]]; then
            echo "✅ Branch name follows the convention."
          else
            echo "❌ Branch name does not follow the required convention."
            echo "Expected format: feature/<username>/<description>"
            exit 1
          fi
